# Deps
FROM containers.chewedfeed.com/docker_hub_cache/library/node:19-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Build
FROM containers.chewedfeed.com/docker_hub_cache/library/node:19-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN yarn build

# Release
FROM containers.chewedfeed.com/docker_hub_cache/library/nginx:alpine AS release
ENV NODE_ENV production
COPY --from=build /app/build /usr/share/nginx/html
COPY ./k8s/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off"]
