# Deps
FROM containers.chewedfeed.com/docker_hub_cache/library/node:19-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Release
FROM containers.chewedfeed.com/docker_hub_cache/library/nide:19-alpine AS release
WORKDIR /app
ENV NODE_ENV production
COPY --from=build /app ./
EXPOSE 3000

CMD ["yarn", "start"]
